### ISSUE TITLE
can not connect docker

### ISSUE THREAD

**Issue by SpectatorNan** [alexsteinerde/docker-client-swift-mac-app#1]
err log:
![image](https://user-images.githubusercontent.com/13959374/162395343-51fbd3df-a138-4df8-92da-f433c6ecdf73.png)

dir files:
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/13959374/162395449-924f8197-ad63-4573-8a62-0d1cf2bfbfb9.png">

system:
macos 12.0.1
M1

**Comment by alexsteinerde** [comment]
I haven't tested the package with M1 Macs yet. 
Can you manually talk to the Docker socket via e.g. curl?

**Comment by SpectatorNan** [comment]
yeah
this is my test:
![image](https://user-images.githubusercontent.com/13959374/162931841-08c7e05f-07e0-49e2-a897-5d9ffa96e2ed.png)

**Comment by alexsteinerde** [comment]
That is strange. Unfortunately I cannot reproduce this issue on my machine. 
Maybe you can try running this in a Linux container to see if this could be related to the macOS Docker installation.

**Comment by SpectatorNan** [comment]
I was able to run healthy using Portainer

**Comment by alexsteinerde** [comment]
First, sorry for the late response but I hadn't much time in the past weeks.

I could reproduce that issue now. Docker required a Host header for each request. I added that missing header to the package. 
Please update the the `docker-swift-client` package to the latest version, that should fix this issue. Does this work for you?

**Comment by SpectatorNan** [comment]
yeah , thanks, it working now.  
but there is have a warning about port

**Comment by alexsteinerde** [comment]
The other warnings/errors are caused by Apple's Network.framework and can be ignored, as far I can tell.
